//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentacion
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
        public string HUid { get; set; }
    
        public virtual historiasDeUsuario historiasDeUsuario { get; set; }
    }
}
