

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoPP.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class patopurificEntitiesRoles : DbContext
{
    public patopurificEntitiesRoles()
        : base("name=patopurificEntitiesRoles")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<permisos> permisos { get; set; }

}

}

