//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class progreso
    {
        public string HU { get; set; }
        public int id { get; set; }
        public System.DateTime fechaCorte { get; set; }
        public int porcentaje { get; set; }
    
        public virtual fechas fechas { get; set; }
        public virtual tarea tarea { get; set; }
    }
}
