//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyecto()
        {
            this.historiasDeUsuario = new HashSet<historiasDeUsuario>();
            this.persona = new HashSet<persona>();
            this.sprint = new HashSet<sprint>();
        }
    
        public string id { get; set; }
        [Display(Name = "Nombre del proyecto")]
        public string nombre { get; set; }
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }
        [Display(Name = "Fecha de Inicio")]
        public System.DateTime fechaInicio { get; set; }
        [Display(Name = "Fecha de finalización")]
        public Nullable<System.DateTime> fechaFinal { get; set; }
        [Display(Name = "Líder del Equipo")]
        public string lider { get; set; }
        [Display(Name = "Estado del proyecto")]
        public string estado { get; set; }


        public string[] listaAgregar { get; set; }
        public string[] listaQuitar { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiasDeUsuario> historiasDeUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<persona> persona { get; set; }
        public virtual persona persona1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sprint> sprint { get; set; }
    }
}
